### ISSUE TITLE
An error message with mikoScore function 

### ISSUE THREAD

**Issue by zyb1984** [NMikolajewicz/scMiko#3]
Dear Professor, 
      I tried to follow the Cell-type annotation using Miko Scoring pipeline with pbmc3k example dataset but with an error message with mikoScore function, and the  error message  was  "2022-09-21 19:11:13: Optimal bin size: 10
2022-09-21 19:11:13: Running cell scoring...
Error in grep(pattern = paste0("^", s, "$"), x = match, ignore.case = TRUE,  :  formal performance’^[CD3D$' wrong"
      And the original code was 
# load package
library(scMiko)
# load Seurat
library(Seurat)
library("SeuratData")
data(pbmc3k)
# cell-type catalog
marker.df <- geneSets[["CellMarker_Hs_Zhang2019"]]
marker.list <- wideDF2namedList(marker.df)
# ensure that all genes are UPPER CASE (human)
marker.list <- lapply(marker.list, toupper)
# only include gene sets with more than 3 markers
marker.list <- marker.list[unlist(lapply(marker.list, length)) > 3]
# step 1
ns.res <- nullScore(object = pbmc3k, assay = DefaultAssay(pbmc3k), n.replicate = 25, 
nbin = 24, min.gs.size = 2, max.gs.size = 200, step.size = 10, nworkers = 16,
 verbose = T, subsample.n = 2000)
# step 2
pbmc_scored <- mikoScore(object = pbmc3k, geneset = marker.list, nbin = 10, 
nullscore = ns.res,  assay = DefaultAssay(pbmc3k), nworkers = 18)
"
and  with variance-gene set-size relationship plot  like this
![image](https://user-images.githubusercontent.com/24197491/191492231-10d9fd7b-fb13-4b55-8dcb-e4aa34d7bb32.png)

**Comment by NMikolajewicz** [comment]
This error arises due to certain gene sets not have ANY genes represented in the seurat object, thereby resulting in the above error. An extra preprocessing step can fix this:

instead of using 
`marker.list <- marker.list[unlist(lapply(marker.list, length)) > 3]`

use
`n.av <- unlist(lapply(marker.list, function(x) sum(x %in% rownames(pbmc3k)))); marker.list <- marker.list[n.av > 3]`

Please let me know if you continue to encounter a problem with this.

**Comment by zyb1984** [comment]
Thank you very much, all had been solved.
