### ISSUE TITLE
different CDI marker genes for cluster optimisation and CDI DEG analysis

### ISSUE THREAD

**Issue by sakatash** [NMikolajewicz/scMiko#7]
Thank you for this interesting and useful package. 
I am running it on my 10x single cell data to identify optimal clustering parameters and marker genes.
I am running the script as they appear in the vignette. First I use the cluster optimisation vignette. Once identified the desired resolution I ran the FindClusters command and ran the CDI DEG analysis. This is when I saw that the top marker genes displayed for resolution optimisation were different then the ones for the DEG analysis.
I am attaching the relevant images:
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/57394243/237062556-b4ec523f-e253-4fb1-b489-ba7cce758e8e.png">
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/57394243/237062581-da9770ea-cb0e-4be8-a002-80f886624bf0.png">

Thank you for your help

**Comment by NMikolajewicz** [comment]
It seems like the plots that you shared in the bottom row were generated for a different cluster resolution than the top row. I'm saying this is because the top row shows 16 clusters (0-15) whereas the bottom results only have 15 clusters (0-14). You should be able to get the same markers if you set the cluster resolution to 1.5 for your analysis.
